<script setup>
import { computed, onMounted, watch, nextTick, ref } from 'vue'
import Icon from './Icon.vue'
import BrandMark from './BrandMark.vue'
import Art from './Art.vue'
import Avatar from './Avatar.vue'
import RoomBadge from './RoomBadge.vue'
import Controls from './Controls.vue'
import TrackList from './TrackList.vue'
import {formatTime,count,MODES} from './domain.mjs'
import {state as s,init,guard,call,toast,navigate,back,showPlayer,setPreference,loadDiscover,refreshDiscover,loadCategory,loadMine,moreMine,showLikes,openCard,openArtist,moreDetail,moreLikes,search,daily,play,like,currentLiked,activeLyric,toggleDesktopLyrics,seek,heart,setMode,login,logout,closeModal,connectRoom,restoreRoom,checkInvite,endRoom,copyInvite,removeQueue,setSleep,roomStatus,roomParticipants,togetherTotalLabel,refreshTogetherStats} from './state.js'
const lyricsEl=ref(null),queueButton=ref(null),modalEl=ref(null),mainEl=ref(null)
let restoreFocus=null
const now=new Date(),date=String(now.getDate()).padStart(2,'0')
const greeting=now.getHours()<6?'夜色正好':now.getHours()<12?'早上好':now.getHours()<18?'下午好':'晚上好'
const tabs=['推荐','歌单','排行榜','新碟','听书 · 播客']
const categories=['全部','华语','欧美','民谣','电子','古典','爵士','轻音乐','夜晚','学习']
const category=ref('全部'),mineTab=ref('创建的歌单')
const themes=[{id:'paper',name:'唱片纸',colors:['#f8f9fb','#ce4547','#20242c']},{id:'ink',name:'夜航',colors:['#111216','#ef7066','#f2f3f7']},{id:'forest',name:'苔原',colors:['#101b18','#94c9aa','#e9f3ec']},{id:'rose',name:'玫瑰灰',colors:['#fbf6f7','#b05377','#392b34']},{id:'blue',name:'海盐',colors:['#f1f7fb','#3f83b5','#1e3448']},{id:'amber',name:'琥珀',colors:['#211c18','#e1b273','#f6ead9']}]
const mineCards=computed(()=>s.mine.playlists.filter(p=>mineTab.value==='创建的歌单'?p.owner===String(s.profile?.userId):p.owner!==String(s.profile?.userId)))
const roomLabel=computed(()=>s.room.id?s.room.connected?'一起听中':'正在重连':'一起听')
const sectionCards=computed(()=>s.tab==='排行榜'?s.discover.charts:s.tab==='新碟'?s.discover.albums:s.tab==='听书 · 播客'?s.discover.radios:s.discover.playlists)
const sectionKey=computed(()=>s.tab==='排行榜'?'charts':s.tab==='新碟'?'albums':s.tab==='听书 · 播客'?'radios':'playlists')
const modeLabel=computed(()=>MODES.find(m=>m.id===s.mode)?.label)
onMounted(()=>{init();window.addEventListener('keydown',onKey)})
watch(()=>s.page,()=>nextTick(()=>mainEl.value?.scrollTo({top:0})))
watch(activeLyric,()=>nextTick(()=>{const line=lyricsEl.value?.querySelector('.lyric-line.active');line?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})}))
watch(()=>s.modal,async(value,old)=>{if(value&&!old)restoreFocus=document.activeElement;await nextTick();if(value)modalEl.value?.querySelector('button,input,select')?.focus();else restoreFocus?.focus()})
watch(()=>s.queueOpen,async open=>{if(open){restoreFocus=document.activeElement;await nextTick();document.querySelector('.queue-sheet button')?.focus()}else restoreFocus?.focus()})
function onKey(e) {
  if(e.key==='Escape'){if(s.modal)closeModal();else if(s.queueOpen)s.queueOpen=false;else if(s.page==='player')back();return}
  if(e.key==='Tab'&&(s.modal||s.queueOpen)) {
    const root=s.modal?modalEl.value:document.querySelector('.queue-sheet')
    const els=[...root?.querySelectorAll('button:not([disabled]),input,select,a[href]')||[]].filter(x=>x.getClientRects().length)
    if(!els.length)return
    if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus()}
  }
  if(e.code==='Space'&&!/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)&&!s.modal){e.preventDefault();document.querySelector('.play-button')?.click()}
}
function cardOpen(p){return guard(p.kind==='artist'?openArtist:openCard)(p)}
async function playCard(p){await (p.kind==='artist'?openArtist:openCard)(p);if(s.detail.tracks.length)await play(s.detail.tracks[0],s.detail.tracks,{id:s.detail.id,title:s.detail.title})}
const syncTime=computed(()=>s.mine.loaded?new Date(s.mine.loaded).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):'尚未同步')
const roomNames=computed(()=>roomParticipants.value.map(m=>m.name).join(' · '))
const headerTitle=computed(()=>s.page==='discover'?'发现音乐':s.page==='mine'?'我的音乐':s.page==='search'?'搜索音乐':s.detail.kind==='radio'?'声音专辑':s.detail.kind==='album'?'专辑详情':'歌单详情')
const headerGreeting=computed(()=>s.page==='discover'?(s.profile?greeting+'，'+s.profile.nickname:'好音乐，从这里开始。'):'')
function setTab(tab){const previous=s.tab;s.tab=tab;if(tab==='推荐'&&previous==='歌单'){category.value='全部';s.discover.playlists=s.discover.pool.slice(0,12);delete s.discover.errors.playlists;if(!s.discover.pool.length)guard(loadDiscover)()}}
function roomOpen(){void refreshTogetherStats(true);if(!s.profile)return guard(login)();s.modal=s.room.id?'room-active':'room'}
async function windowFullscreen(){s.fullscreen=await window.cloud.window('fullscreen')}
async function chooseTheme(theme){await setPreference('theme',theme);toast('已切换到'+themes.find(t=>t.id===theme).name)}
</script>

<template>
<div class="app" :data-theme="s.prefs.theme" :data-font="s.prefs.font" :class="{'player-visible':s.page==='player'}">
  <header class="app-header" v-if="s.page!=='player'">
    <button class="wordmark" aria-label="云伴首页" @click="navigate('discover')"><BrandMark :size="32" /><span>云伴<small>音乐，与你。</small></span></button>
    <div class="header-left"><button v-if="s.page!=='discover'" class="icon-button" aria-label="返回" @click="back"><Icon name="left" /></button><div class="header-heading"><h1>{{headerTitle}}</h1><p v-if="headerGreeting">{{headerGreeting}}</p></div></div>
    <form class="search-box" @submit.prevent="guard(search)()"><Icon name="search" :size="17" /><input aria-label="搜索音乐" v-model="s.search.query" placeholder="搜索音乐、歌单、播客" maxlength="200"><button v-if="s.search.query" type="button" class="search-clear" aria-label="清空搜索" @click="s.search.query=''"><Icon name="close" :size="14" /></button></form>
    <button class="room-chip" :class="{connected:s.room.id}" @click="roomOpen"><Icon name="headphones" :size="17" />{{roomLabel}}<i v-if="s.room.id"></i></button>
    <button class="icon-button skin-button" title="皮肤与外观" aria-label="更换皮肤" @click="s.modal='themes'"><Icon name="palette" /></button>
    <button class="profile-button" :aria-label="s.profile?'我的':'登录网易云'" @click="s.profile?(navigate('mine'),guard(loadMine)()):guard(login)()"><Avatar :src="s.profile?.avatarUrl" :name="s.profile?.nickname" :size="30" /><span class="profile-caption">{{s.profile?'我的':'登录'}}</span></button>
  </header>

  <main v-if="s.page!=='player'" ref="mainEl" class="main-scroll">
    <div v-if="s.page==='discover'" class="discover page-width">
      
      <nav class="discovery-tabs" aria-label="发现分类"><button v-for="tab in tabs" :key="tab" :class="{active:s.tab===tab}" @click="setTab(tab)">{{tab}}</button><button class="refresh text-button" :aria-label="s.tab==='推荐'||s.tab==='歌单'?'换一批歌单':'更新内容'" :disabled="s.discover.loading" :class="{loading:s.discover.loading}" @click="guard(refreshDiscover)(s.tab,category)"><Icon name="refresh" :size="16" /><span>{{s.discover.loading?'加载中':s.tab==='推荐'||s.tab==='歌单'?'换一批':'更新'}}</span></button></nav>
      <p v-if="s.discover.errors[sectionKey]&&sectionCards.length" class="inline-error" role="alert">{{s.discover.errors[sectionKey]}} · 当前内容已保留</p>
      <div v-if="s.tab==='推荐'" class="feature-grid">
        <button class="editorial-feature" @click="guard(daily)()"><span class="daily-icon"><Icon name="calendar" :size="23" /><b>{{date}}</b></span><span class="feature-copy"><strong>每日推荐</strong><small>{{s.profile?'根据你的听歌口味，每天更新':'登录，听属于你的每日推荐'}}</small></span><Icon name="right" :size="18" /></button>
        <button class="heart-feature" :disabled="!!s.room.id||s.room.busy" :title="s.room.id?'结束一起听后可开启心动模式':'开启心动推荐'" @click="guard(heart)()"><span class="shortcut-icon"><Icon name="heart" :size="23" /></span><span><strong>心动模式</strong><small>{{s.room.id?'一起听期间不可用':'喜欢的歌，也有新的惊喜'}}</small></span><Icon name="right" :size="18" /></button>
        <button class="together-feature" @click="roomOpen"><span class="shortcut-icon"><Icon name="headphones" :size="23" /></span><span><strong>{{s.room.id?'回到一起听':'一起听'}}</strong><small>{{s.room.id?roomNames:'邀请一个人，分享此刻的音乐'}}</small></span><Icon name="right" :size="18" /></button>
      </div>
      <div v-if="s.tab==='歌单'" class="category-chips"><button v-for="cat in categories" :key="cat" :class="{active:category===cat}" @click="category=cat;guard(loadCategory)(cat)">{{cat}}</button></div>
      <div class="section-heading"><div><span class="eyebrow">{{s.tab==='排行榜'?'实时榜单':s.tab==='新碟'?'新鲜发行':s.tab==='听书 · 播客'?'声音与故事':'为你精选'}}</span><h2>{{s.tab==='推荐'?(s.profile?'推荐歌单':'精选歌单'):s.tab==='歌单'?category+'歌单':s.tab==='听书 · 播客'?'播客与声音':s.tab}}</h2></div><span class="section-caption">{{s.tab==='排行榜'?'网易云榜单 · 持续更新':s.tab==='听书 · 播客'?'有声书、音乐电台与播客':'由网易云音乐提供内容'}}</span></div>
      <div v-if="s.discover.loading&&!sectionCards.length" class="cards-grid skeleton-grid" aria-label="正在加载内容"><div v-for="i in 6" :key="i"><div></div><span></span><small></small></div></div>
      <div v-else-if="s.discover.errors[sectionKey]&&!sectionCards.length" class="empty-state"><Icon name="refresh" :size="28" /><h3>暂时没能取到这部分内容</h3><p>{{s.discover.errors[sectionKey]}}</p><button class="secondary" @click="guard(loadDiscover)()">重新加载</button></div>
      <div v-else-if="!sectionCards.length" class="empty-state"><Icon name="music" :size="28" /><p>网易云暂时没有返回内容</p><button class="secondary" @click="guard(loadDiscover)()">刷新</button></div>
      <div v-else class="cards-grid" :class="{'chart-grid':s.tab==='排行榜'}">
        <article v-for="(p,i) in sectionCards" :key="p.id" :data-card-id="p.id" class="cover-card"><div class="cover-wrap"><button class="cover-open" :aria-label="'打开 '+p.name" @click="cardOpen(p)"><Art :src="p.cover" :name="p.name" /><span v-if="p.plays" class="play-count"><Icon name="play" :size="12" />{{count(p.plays)}}</span><span v-if="s.tab==='排行榜'" class="chart-index">{{String(i+1).padStart(2,'0')}}</span></button><button class="card-play" :aria-label="'播放 '+p.name" @click="guard(playCard)(p)"><Icon name="play" :size="20" /></button></div><h3><button :title="p.name" @click="cardOpen(p)">{{p.name}}</button></h3><p>{{p.update||p.creator||p.description||'网易云音乐歌单'}}</p><ol v-if="s.tab==='排行榜'&&p.preview?.length"><li v-for="(t,j) in p.preview" :key="j"><span>{{j+1}}</span>{{t.first}} <small>{{t.second}}</small></li></ol></article>
      </div>
      <template v-if="s.tab==='推荐'"><div class="section-heading"><div><span class="eyebrow">热门趋势</span><h2>热门榜单</h2></div><button class="text-button" @click="setTab('排行榜')">全部榜单 <Icon name="arrow" :size="17" /></button></div><div class="compact-charts"><button v-for="(p,i) in s.discover.charts.slice(0,3)" :key="p.id" @click="cardOpen(p)"><Art :src="p.cover" :name="p.name" /><div><span class="eyebrow">官方榜单</span><h3>{{p.name}}</h3><p>{{p.preview?.[0]?.first||p.update||'查看最新榜单'}}</p></div><Icon name="right" :size="18" /></button></div></template>
      <template v-if="s.tab==='听书 · 播客'"><div class="section-heading"><div><span class="eyebrow">节目推荐</span><h2>推荐节目</h2></div><div class="category-chips"><button @click="guard(async()=>{const r=await call('dj_recommend_type',{type:'10001'});s.discover.radios=(r.djRadios||[]).map(p=>({id:String(p.id),name:p.name,cover:p.picUrl,kind:'radio',count:p.programCount,description:p.desc}))})()">有声书</button><button @click="guard(loadDiscover)()">全部声音</button></div></div><TrackList :tracks="s.discover.programs" :source="{id:'0',title:'推荐节目'}" /></template>
      <footer class="page-footer"><span>云伴 · 独立音乐客户端</span><button @click="s.modal='about'">关于与致谢 <Icon name="arrow" :size="14" /></button></footer>
    </div>

    <div v-else-if="s.page==='mine'" class="mine page-width">
      <div class="page-top"><span class="eyebrow">音乐资料库</span><button class="text-button" @click="s.modal='settings'"><Icon name="settings" :size="16" />偏好设置</button></div>
      <div class="mine-heading"><Avatar :src="s.profile?.avatarUrl" :name="s.profile?.nickname" :size="64" /><div><span class="eyebrow">我的音乐</span><h1>{{s.profile?.nickname||'这里，属于你的音乐。'}}</h1><p>{{s.profile?'歌单和喜欢的音乐，同步自你的网易云账号。':'登录网易云音乐，接着听你的收藏。'}}</p></div><button v-if="s.profile" class="secondary" :disabled="s.mine.loading" @click="guard(loadMine)()"><Icon name="refresh" :size="16" />{{s.mine.loading?'同步中…':'同步账号'}}</button><button v-else class="primary" @click="guard(login)()">登录网易云</button></div>
      <div v-if="s.mine.error" class="inline-error" role="alert">{{s.mine.error}}<button @click="guard(loadMine)()">重试</button></div>
      <div class="personal-shortcuts"><button class="liked-shortcut" @click="guard(showLikes)()"><div><Icon name="heart" :size="32" /></div><span><h2>我喜欢的音乐</h2><p>{{s.mine.likes.length}} 首 <span>· 与账号同步</span></p></span><Icon name="right" /></button><button class="heart-shortcut" :disabled="!!s.room.id||s.room.busy" :title="s.room.id?'结束一起听后可开启':'开启心动推荐'" @click="guard(heart)()"><Icon name="heart" :size="30" /><span><h2>心动模式</h2><p>{{s.room.id?'结束一起听后可开启':'重逢喜欢，遇见新歌。'}}</p></span><Icon name="right" /></button></div>
      <div class="section-heading mine-tabs"><div class="discovery-tabs"><button v-for="t in ['创建的歌单','收藏的歌单']" :key="t" :class="{active:mineTab===t}" @click="mineTab=t">{{t}}</button></div><span class="section-caption">{{mineCards.length}} 个歌单</span></div>
      <div v-if="s.mine.loading&&!s.mine.playlists.length" class="empty-state"><div class="spinner"></div><p>正在同步你的网易云账号…</p></div>
      <div v-else-if="!mineCards.length" class="empty-state"><Icon name="music" :size="32" /><h3>{{s.profile?'这里还没有歌单':'登录后，你的歌单会在这里'}}</h3><p>{{s.mine.error?'同步遇到问题，请重试。':'红心操作会同步到网易云「我喜欢的音乐」。'}}</p></div>
      <div v-else class="cards-grid"><article v-for="p in mineCards" :key="p.id" :data-card-id="p.id" class="cover-card"><div class="cover-wrap"><button class="cover-open" :aria-label="'打开 '+p.name" @click="cardOpen(p)"><Art :src="p.cover" :name="p.name" /></button><button class="card-play" :aria-label="'播放 '+p.name" @click="guard(playCard)(p)"><Icon name="play" :size="20" /></button></div><h3><button :title="p.name" @click="cardOpen(p)">{{p.name}}</button></h3><p>{{p.count}} 首 · {{p.creator}}</p></article></div>
      <button v-if="s.mine.more" class="secondary load-more" @click="guard(moreMine)()">加载更多歌单</button>
      <footer class="page-footer"><span>{{s.mine.loaded?'最近同步 '+syncTime:'尚未同步'}}</span><button v-if="s.profile" @click="s.modal='logout'">退出登录</button></footer>
    </div>

    <div v-else-if="s.page==='detail'" class="detail page-width">
      <div class="page-top"><span class="eyebrow">{{s.detail.kind==='radio'?'声音专辑':s.detail.kind==='album'?'专辑':'音乐收藏'}}</span></div>
      <div class="detail-heading"><Art :src="s.detail.cover" :name="s.detail.title" /><div><span class="eyebrow">{{s.detail.kind==='radio'?'声音专辑':s.detail.kind==='album'?'专辑':'歌单'}}</span><h1>{{s.detail.title}}</h1><p class="detail-byline">{{s.detail.creator}} <i>·</i> {{s.detail.total}} {{s.detail.kind==='radio'?'集':'首'}}</p><p class="detail-description">{{s.detail.description||'暂无简介'}}</p><button class="primary" :disabled="!s.detail.tracks.length" @click="guard(play)(s.detail.tracks[0],s.detail.tracks,{id:s.detail.id,title:s.detail.title})"><Icon name="play" :size="18" />播放全部</button></div></div>
      <div v-if="s.detail.error" class="inline-error" role="alert">{{s.detail.error}}<button @click="cardOpen({id:s.detail.id,name:s.detail.title,kind:s.detail.kind,cover:s.detail.cover})">重试</button></div>
      <div v-if="s.detail.loading" class="empty-state"><div class="spinner"></div><p>正在打开这份音乐…</p></div><TrackList v-else :tracks="s.detail.tracks" :source="{id:s.detail.id,title:s.detail.title}" />
      <div v-if="!s.detail.loading&&!s.detail.tracks.length&&!s.detail.error" class="empty-state"><p>这份列表暂时没有可显示的内容。</p></div>
      <button v-if="s.detail.more" class="secondary load-more" @click="guard(s.detail.kind==='likes'?moreLikes:moreDetail)()">加载更多（{{s.detail.tracks.length}} / {{s.detail.total}}）</button>
    </div>

    <div v-else-if="s.page==='search'" class="search-page page-width">
      <div class="page-top"><span class="eyebrow">搜索结果</span></div><h1>“{{s.search.query}}”<small>的搜索结果</small></h1>
      <nav class="discovery-tabs" aria-label="搜索分类"><button v-for="t in [{id:1,name:'歌曲'},{id:1000,name:'歌单'},{id:100,name:'歌手'},{id:10,name:'专辑'},{id:1009,name:'声音'}]" :key="t.id" :class="{active:s.search.type===t.id}" @click="guard(search)(t.id)">{{t.name}}</button><span class="section-caption">{{s.search.total}} 个结果</span></nav>
      <div v-if="s.search.error" class="inline-error">{{s.search.error}}<button @click="guard(search)()">重试</button></div>
      <TrackList v-if="s.search.type===1" :tracks="s.search.tracks" :source="{id:'0',title:'搜索结果'}" />
      <div v-else class="cards-grid"><article v-for="p in s.search.cards" :key="p.id" :data-card-id="p.id" class="cover-card"><div class="cover-wrap"><button class="cover-open" :aria-label="'打开 '+p.name" @click="cardOpen(p)"><Art :src="p.cover" :name="p.name" /></button><button class="card-play" :aria-label="'播放 '+p.name" @click="guard(playCard)(p)"><Icon name="play" :size="20" /></button></div><h3><button :title="p.name" @click="cardOpen(p)">{{p.name}}</button></h3><p>{{p.creator}}</p></article></div>
      <div v-if="s.search.loading" class="empty-state"><div class="spinner"></div><p>正在寻找…</p></div><div v-else-if="!s.search.error&&!s.search.tracks.length&&!s.search.cards.length" class="empty-state"><Icon name="search" :size="30" /><h3>还没找到这个声音</h3><p>试试其他关键词。</p></div>
      <button v-if="s.search.more" class="secondary load-more" :disabled="s.search.loading" @click="guard(search)(s.search.type,true)">更多结果</button>
    </div>
  </main>

  <section v-else class="full-player" aria-label="完整播放页">
    <div class="player-top"><button class="player-back text-button" @click="back"><Icon name="down" />收起播放页</button><RoomBadge @open="roomOpen" /><div><button class="icon-button" aria-label="更换皮肤" @click="s.modal='themes'"><Icon name="palette" /></button><button class="icon-button" aria-label="切换全屏" @click="guard(windowFullscreen)()"><Icon name="fullscreen" /></button></div></div>
    <div class="player-stage"><div class="album-side"><div class="album-frame" :class="{spinning:s.playing}"><Art :src="s.current?.album.cover" :name="s.current?.album.name" /></div><div class="player-title"><span class="eyebrow">{{s.source.title||'NOW PLAYING'}}</span><h1 :title="s.current?.name">{{s.current?.name||'还没有播放音乐'}}</h1><p :title="s.current?s.current.artists.map(a=>a.name).join(' / ')+' · '+s.current.album.name:''">{{s.current?s.current.artists.map(a=>a.name).join(' / '):'从发现或我的歌单开始播放'}}<span v-if="s.current?.album.name"> · {{s.current.album.name}}</span></p></div><div class="player-actions"><button class="icon-button like" :class="{liked:currentLiked}" :disabled="!s.current||!!s.current.program" :aria-label="currentLiked?'取消喜欢':'喜欢当前歌曲'" @click="guard(like)()"><Icon name="heart" :size="25" /></button><span>{{currentLiked?'已喜欢':s.current?.program?'声音节目':'喜欢这首歌'}}</span><span v-if="s.mode==='heart'" class="recommend-label">心动推荐</span></div></div>
      <div class="lyrics-panel"><div class="lyrics-caption"><span class="eyebrow">{{s.current?.artists.map(a=>a.name).join(' / ')||'正在播放'}}</span><span>{{s.current?.program?'声音节目':'歌词'}}</span></div><div ref="lyricsEl" class="lyrics-scroll"><template v-if="s.lyrics.length"><button v-for="(line,i) in s.lyrics" :key="i" class="lyric-line" :class="{active:activeLyric===i}" :aria-label="'跳转到 '+formatTime(line.time)+' '+line.text" @click="guard(seek)(line.time)"><span>{{line.text}}</span><small v-if="line.translation">{{line.translation}}</small></button></template><div v-else class="no-lyrics"><span class="lyric-mark">♪</span><h2>{{s.lyricLoading?'正在加载歌词':s.current?s.current.program?'声音节目':'暂无歌词':'选择一首音乐'}}</h2><p>{{s.current?'继续欣赏音乐':'打开歌单开始播放'}}</p><button v-if="!s.current" class="secondary" @click="navigate('discover')">去发现音乐</button></div></div></div>
    </div>
    <div class="player-bottom"><div class="player-progress"><span>{{formatTime(s.progress)}}</span><input aria-label="播放进度" type="range" min="0" :max="s.duration||1" step="0.1" :value="s.progress" :disabled="!s.current||s.loading" :style="{'--progress':(s.progress/(s.duration||1)*100)+'%'}" @change="guard(seek)(Number($event.target.value))"><span>{{formatTime(s.duration)}}</span></div><div class="player-control-line"><button class="text-button mode-caption" @click="s.modal='modes'"><Icon :name="s.mode==='heart'?'heart':s.mode" :size="17" />{{modeLabel}}</button><Controls large /><div class="player-options"><button class="icon-button lyrics-toggle" :class="{active:s.desktopLyrics}" :aria-label="s.desktopLyrics?'关闭桌面歌词':'开启桌面歌词'" :title="s.desktopLyrics?'关闭桌面歌词':'开启桌面歌词'" :aria-pressed="s.desktopLyrics" :disabled="s.desktopLyricsBusy" @click="guard(toggleDesktopLyrics)()">词</button><button class="icon-button queue-toggle" :class="{active:s.queueOpen}" aria-label="打开播放列表" @click="s.queueOpen=!s.queueOpen"><Icon name="queue" :size="22" /></button><button class="icon-button" aria-label="定时停止" :class="{active:s.sleep}" @click="s.modal='sleep'"><Icon name="clock" /></button><label class="volume-control"><Icon name="volume" :size="20" /><input aria-label="音量" type="range" min="0" max="1" step="0.01" :value="s.prefs.volume" @input="guard(setPreference)('volume',Number($event.target.value))"></label></div></div><div v-if="s.error" class="player-error" role="alert">{{s.error}}</div></div>
  </section>

  <footer v-if="s.page!=='player'" class="mini-player" aria-label="底部播放器">
    <div class="mini-left"><button class="mini-track" aria-label="打开播放页" @click="showPlayer"><Art :src="s.current?.album.cover" :name="s.current?.name" /><span><strong :title="s.current?.name">{{s.current?.name||'还没有播放音乐'}}</strong><small>{{s.current?s.current.artists.map(a=>a.name).join(' / '):'从发现或我的歌单开始播放'}}</small></span></button><button class="icon-button like mini-like" :class="{liked:currentLiked}" :disabled="!s.current||!!s.current.program" :aria-label="currentLiked?'取消喜欢':'喜欢当前歌曲'" @click="guard(like)()"><Icon name="heart" :size="20" /></button></div>
    <div class="mini-center"><Controls /><div class="mini-progress"><span>{{formatTime(s.progress)}}</span><input aria-label="播放进度" type="range" min="0" :max="s.duration||1" step="0.1" :value="s.progress" :disabled="!s.current||s.loading" :style="{'--progress':s.progress/(s.duration||1)*100+'%'}" @change="guard(seek)(Number($event.target.value))"><span>{{formatTime(s.duration)}}</span></div></div>
    <div class="mini-right"><button class="mode-control" aria-label="播放模式" :title="modeLabel" @click="s.modal='modes'"><Icon :name="s.mode==='heart'?'heart':s.mode" :size="18" /><span>{{modeLabel}}</span></button><RoomBadge compact @open="roomOpen" /><label class="volume-control"><Icon name="volume" :size="19" /><input aria-label="音量" type="range" min="0" max="1" step="0.01" :value="s.prefs.volume" @input="guard(setPreference)('volume',Number($event.target.value))"></label><button class="icon-button lyrics-toggle" :class="{active:s.desktopLyrics}" :aria-label="s.desktopLyrics?'关闭桌面歌词':'开启桌面歌词'" :title="s.desktopLyrics?'关闭桌面歌词':'开启桌面歌词'" :aria-pressed="s.desktopLyrics" :disabled="s.desktopLyricsBusy" @click="guard(toggleDesktopLyrics)()">词</button><button class="icon-button queue-toggle" :class="{active:s.queueOpen}" aria-label="打开播放列表" @click="s.queueOpen=!s.queueOpen"><Icon name="queue" :size="20" /></button><span class="toolbar-divider"></span><button ref="queueButton" class="icon-button expand-player" aria-label="展开完整播放页" @click="showPlayer"><Icon name="up" :size="22" /></button></div>
    <div v-if="s.error" class="mini-error" role="alert">{{s.error}}</div>
  </footer>

  <div v-if="s.queueOpen" class="queue-backdrop" @click.self="s.queueOpen=false"><section class="queue-sheet" role="dialog" aria-modal="true" aria-label="播放列表"><header><div><span class="eyebrow">{{s.room.id?'一起听':'播放队列'}}</span><h2>{{s.room.id?'共同播放列表':'接下来播放'}} <small>{{s.queue.length}} 首</small></h2></div><button class="icon-button" aria-label="关闭播放列表" @click="s.queueOpen=false"><Icon name="close" /></button></header><p class="queue-context">{{s.source.title||'你的播放队列'}} <span>·</span> {{modeLabel}}</p><div class="queue-list"><div v-if="!s.queue.length" class="empty-state"><Icon name="queue" :size="30" /><p>选一首歌，队列就会从这里开始。</p></div><div v-for="(t,i) in s.queue" :key="t.id+'-'+i" class="queue-row" :class="{current:s.current?.id===t.id}"><span>{{String(i+1).padStart(2,'0')}}</span><button :aria-label="'播放 '+t.name" @click="guard(play)(t)"><Art :src="t.album.cover" :name="t.name" /><span><strong>{{t.name}}</strong><small>{{t.artists.map(a=>a.name).join(' / ')}}</small></span></button><span v-if="t.recommended" class="recommend-label">推荐</span><span class="queue-time">{{formatTime(t.duration)}}</span><button v-if="!s.room.id" class="icon-button" :aria-label="'移除 '+t.name" @click="removeQueue(t.id)"><Icon name="close" :size="15" /></button></div></div></section></div>

  <div v-if="s.modal" class="modal-backdrop" @click.self="closeModal"><section ref="modalEl" class="modal" :class="{'theme-modal':s.modal==='themes'}" role="dialog" aria-modal="true" :aria-label="s.modal==='login'?'登录网易云音乐':s.modal==='themes'?'选择皮肤':s.modal.startsWith('room')?'一起听房间':'偏好与设置'"><button class="modal-close icon-button" aria-label="关闭弹窗" @click="closeModal"><Icon name="close" /></button>
    <template v-if="s.modal==='login'"><span class="eyebrow">网易云音乐账号</span><h2>扫码登录</h2><p>使用网易云音乐 App 扫码登录</p><div class="qr-frame"><img v-if="s.login.image" :src="s.login.image" alt="网易云登录二维码"><div v-else class="spinner"></div></div><p class="qr-status" role="status">{{s.login.message}}</p><button class="text-button" :disabled="s.login.busy" @click="guard(login)()"><Icon name="refresh" :size="16" />刷新二维码</button><p class="modal-note">歌单、红心喜欢与账号同步。<br>登录凭据保存在本机，不会发送到第三方服务。</p></template>
    <template v-else-if="s.modal==='themes'"><span class="eyebrow">外观</span><h2>皮肤</h2><p>为你的播放器选择外观。</p><div class="theme-grid"><button v-for="t in themes" :key="t.id" :aria-label="t.name+'皮肤'" :class="{selected:s.prefs.theme===t.id}" @click="guard(chooseTheme)(t.id)"><div class="theme-preview" :style="{background:t.colors[0],color:t.colors[2]}"><span class="theme-record" :style="{background:t.colors[2]}"><i :style="{background:t.colors[1]}"></i></span><span class="theme-lines"><i :style="{background:t.colors[2]}"></i><i :style="{background:t.colors[1]}"></i><i :style="{background:t.colors[2]}"></i></span></div><span>{{t.name}}<Icon v-if="s.prefs.theme===t.id" name="check" :size="17" /></span></button></div></template>
    <template v-else-if="s.modal==='settings'"><span class="eyebrow">偏好设置</span><h2>播放与外观</h2><label class="setting-row">播放音质<select :value="s.prefs.quality" @change="guard(setPreference)('quality',$event.target.value)"><option value="standard">标准</option><option value="exhigh">极高</option><option value="lossless">无损</option><option value="hires">Hi-Res</option></select></label><p class="modal-note">实际音质由你的网易云账号权益和歌曲可用音源决定，下一首生效。</p><button class="setting-row text-button" @click="s.modal='themes'">皮肤 <Icon name="right" /></button><button class="setting-row text-button" @click="s.modal='sleep'">定时停止 <span>{{s.sleep?s.sleep+' 分钟':'未开启'}}</span></button><button class="setting-row text-button" @click="s.modal='about'">关于与致谢 <Icon name="right" /></button><p class="modal-note">凭据保存：{{s.storage||'正在检查'}}</p></template>
    <template v-else-if="s.modal==='room'"><span class="eyebrow">一起听</span><h2>与听友一起听</h2><p v-if="s.mode==='heart'" class="room-mode-note">加入房间将退出心动模式，切换为共同队列。</p><p>可加入手机网易云 App 的双人一起听房间。</p><div v-if="s.togetherStats.peerId" class="together-total"><span>与 {{s.togetherStats.peerName}} 累计一起听</span><strong>{{s.togetherStats.totalSeconds!==null?togetherTotalLabel:s.togetherStats.loading?'正在同步…':'暂未取得累计时长'}}</strong><small>{{s.togetherStats.error?(s.togetherStats.totalSeconds!==null?'暂时无法更新，已保留上次结果':'暂时无法取得累计时长，请重试'):'网易云账号累计记录'}}</small><button class="text-button" :disabled="s.togetherStats.loading" @click="refreshTogetherStats(true)"><Icon name="refresh" :size="13" />{{s.togetherStats.loading?'同步中':'刷新累计时长'}}</button></div><label class="input-label">邀请链接<input v-model="s.room.invite" aria-label="一起听邀请链接" placeholder="粘贴网易云一起听邀请链接" @input="s.room.checked=null"></label><div class="modal-actions"><button class="secondary" :disabled="!s.room.invite||s.room.busy" @click="guard(checkInvite)()">检查邀请</button><button class="primary" :disabled="!s.room.invite||s.room.busy" @click="guard(connectRoom)(false)">加入房间</button></div><p v-if="s.room.checked" class="modal-note">{{s.room.checked.valid?'邀请可用，点击加入即可连接。':'房间已结束，请使用新的邀请。'}}</p><div class="divider"><span>或者</span></div><button class="secondary full-width" :disabled="s.room.busy" @click="guard(connectRoom)(true)">{{s.room.busy?'正在连接…':'创建房间，邀请听友'}}</button><button class="text-button room-restore" :disabled="s.room.busy" @click="guard(restoreRoom)()">恢复当前账号的房间</button><p class="modal-note">双方使用各自账号的歌曲权益。<br>房间状态定期同步，网络恢复后自动重连。</p></template>
    <template v-else-if="s.modal==='room-active'"><span class="eyebrow">一起听房间</span><h2>正在一起听</h2><div class="room-members"><div v-for="m in roomParticipants" :key="m.id"><Avatar :src="m.avatar" :name="m.name" :size="60" /><strong>{{m.name}}</strong><span>{{m.id===String(s.profile?.userId)?'你':'听友'}}</span></div></div><p role="status">{{roomStatus}}</p><div v-if="s.togetherStats.peerId" class="together-total"><span>与 {{s.togetherStats.peerName}} 累计一起听</span><strong>{{s.togetherStats.totalSeconds!==null?togetherTotalLabel:s.togetherStats.loading?'正在同步…':'暂未取得累计时长'}}</strong><small>{{s.togetherStats.error?(s.togetherStats.totalSeconds!==null?'暂时无法更新，已保留上次结果':'暂时无法取得累计时长，请重试'):'网易云账号累计记录'}}</small><button class="text-button" :disabled="s.togetherStats.loading" @click="refreshTogetherStats(true)"><Icon name="refresh" :size="13" />{{s.togetherStats.loading?'同步中':'刷新累计时长'}}</button></div><button class="primary full-width" @click="guard(copyInvite)()"><Icon name="copy" :size="17" />复制邀请链接</button><button class="text-button room-end" @click="s.modal='room-end'">结束一起听</button></template>
    <template v-else-if="s.modal==='room-end'"><h2>结束这次一起听？</h2><p>结束双方房间，回到单人播放。<br>保留当前歌曲、进度与播放队列。</p><div class="modal-actions"><button class="secondary" @click="s.modal='room-active'">继续听</button><button class="primary" :disabled="s.room.busy" @click="guard(endRoom)()">确认结束</button></div></template>
    <template v-else-if="s.modal==='sleep'"><span class="eyebrow">播放设置</span><h2>定时停止</h2><p>到时会暂停播放。</p><div class="sleep-options"><button v-for="m in [0,15,30,60,90]" :key="m" :class="{selected:s.sleep===m}" @click="setSleep(m);closeModal();toast(m?'将在 '+m+' 分钟后暂停':'已取消定时停止')">{{m?m+' 分钟':'关闭定时'}}</button></div></template>
    <template v-else-if="s.modal==='modes'"><h2>播放模式</h2><div class="mode-options"><button v-for="m in MODES" :key="m.id" :disabled="!!s.room.id&&['heart','shuffle'].includes(m.id)" @click="guard(setMode)(m.id);closeModal()"><Icon :name="m.id==='heart'?'heart':m.id" /><span>{{m.label}}<small>{{s.room.id&&['heart','shuffle'].includes(m.id)?'一起听使用共同队列，结束后可开启':m.id==='sequence'?'顺序播放，队列结束后衔接推荐':m.id==='repeat'?'重复播放当前歌曲':m.id==='shuffle'?'随机播放队列中的歌曲':'喜欢的音乐与网易云心动推荐'}}</small></span><Icon v-if="s.mode===m.id" name="check" /></button></div></template>
    <template v-else-if="s.modal==='logout'"><h2>退出当前账号？</h2><p>本机登录凭据会被清除；你的网易云歌单与喜欢会保留。</p><div class="modal-actions"><button class="secondary" @click="closeModal">取消</button><button class="primary" @click="guard(logout)()">退出登录</button></div></template>
    <template v-else-if="s.modal==='about'"><span class="eyebrow">CLOUDTOGETHER / 0.1.0</span><h2>云伴</h2><p>为音乐留一处空间。</p><p class="about-copy">独立编写的网易云音乐桌面客户端。界面、播放状态、账号管理、桌面桥接与一起听逻辑均为本项目实现。</p><div class="credits"><h3>接口与开源致谢</h3><a href="https://github.com/NeteaseCloudMusicApiEnhanced/api-enhanced" target="_blank" rel="noreferrer">NeteaseCloudMusicApiEnhanced <Icon name="arrow" :size="16" /></a><p>网易云接口适配层 · MIT<br>同时感谢原项目 Binaryify/NeteaseCloudMusicApi 及贡献者。</p><p>Electron · Vue · Vite · Zod · QRCode<br>字体：Noto / 思源系列 · SIL Open Font License</p></div><p class="modal-note">非网易云官方客户端。歌曲与节目由网易云提供；播放遵循账号权益。第三方依赖的完整许可见源码包 THIRD_PARTY_NOTICES.md。</p></template>
  </section></div>
  <div v-if="s.toast" class="toast" :data-kind="s.toastKind" role="status"><Icon :name="s.toastKind==='error'?'warning':'check'" :size="17" /><span>{{s.toast}}</span></div>
</div>
</template>
